title: Maravedi
description: $Father | ? { $_.InfoSecFactotum -And $_.PowerShellJunkie }
show_sidebar: true
google_analytics:
theme: jekyll-theme-architect
plugins:
  - jekyll-gist
excerpt_separator: "<!-- more -->"
